version: '3'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
#    ports:
#      - 9333:9333
#      - 19333:19333
    command: "master -ip=master"
    volumes:
      - ./master_data:/data
  volume:
    image: chrislusf/seaweedfs # use a remote image
#    ports:
#      - 8080:8080
#      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080'
    depends_on:
      - master
    volumes:
      - ./volume_data:/data
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
#      - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    volumes:
      - ./filer_data:/data/filerldb2
#  cronjob:
#    image: chrislusf/seaweedfs # use a remote image
#    command: 'cronjob'
#    environment:
#      # Run re-replication every 2 minutes
#      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
#      WEED_MASTER: master:9333 # Default: localhost:9333
#    depends_on:
#      - master
#      - volume
#    volumes:
#      - ./cronjob_data:/data
#  s3:
#    image: chrislusf/seaweedfs # use a remote image
#    ports:
#      - 8333:8333
#    command: 's3 -filer="filer:8888"'
#    depends_on:
#      - master
#      - volume
#      - filer
#    volumes:
#      - ./s3_data:/data
